### ISSUE TITLE
Follow Camera is too slow

### ISSUE THREAD

**Issue by SoySmash** [studio-minus/ppg-bug-reports#75] opened 2021-08-02 00:31 UTC
**Describe the bug**
Follow camera is too slow, cant keep up sometimes

**Clearly describe how to reproduce the bug**
if you create something insanely fast, the follow camera sometimes cannot keep up with the moving object, and eventually all you can see is whats behind it because the follow camera is so slow

**Mod list**
I have no mods currently installed.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.20
 - GPU: I dont know
 - CPU: I dont know

**Comment by mestiez** [comment] 2021-08-02 12:33
I cannot reproduce this. I have created an object that is incredibly fast and reaches the other side of the largest map in under a second. The camera keeps up just fine... What are you doing exactly?

**Comment by mestiez** [comment] 2021-08-09 10:47
Closing until I get a response

**Closed by mestiez** 2021-08-09 10:47 UTC
Labels: bug, unclear
