### ISSUE TITLE
Found a way to make new maps by abusing the physics

### ISSUE THREAD

**Issue by Tye-Evans2** [studio-minus/ppg-bug-reports#69] opened 2021-07-28 11:26 UTC
I made a circle out of metal and had a pin in the middle of it so it would rotate and put some humans inside with some weapons and spun the circle and it eventually started glitching really badly. The metal was teleporting everywhere and went red hot with friction until the screen (besides the blood) went black. I zoomed out and realised a chunk of the map had somehow been dragged out of the ground forming a new very large piece of land.

I have not been able to reproduce the issue but did record a video that included some of the process of the glitch https://youtu.be/v30zWYvNTsc
# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.19042) 64bit

 - **CPU**: Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz

 - **GPU**: NVIDIA GeForce GTX 1650

 - **Memory**: 7 GB

## All loaded mods

	Skullex(jamesH_2), Aspa102, Kassjak-Scream mod-2494555615 v1.0 for game v1.11
		Currently inactive

	Gun_O-Futuristic Weapons Mod +-2494447929 v0.3 for game v1.17
		Currently inactive

## Last log

```
0s [LOG] Control scheme file not found.
0s [EXCEPTION] FileNotFoundException: Could not find file "C:\Program Files (x86)\Steam\steamapps\common\People Playground\ControlScheme.json"
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
System.IO.File.ReadAllText (System.String path) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
InputSystem.Load () (at <2b83b641b72c48329c8bc2399bd00c95>:0)
UnityEngine.Debug:LogException(Exception)
InputSystem:Load()
ControlSchemeEditorBehaviour:LoadInputSystem()
ControlSchemeEditorBehaviour:Awake()
UnityEngine.GameObject:SetActive(Boolean)
MenuController:Awake()

0s [LOG] Steamworks initialised
0s [LOG] Steam login: True
0s [LOG] Jukebox not found. Can't load custom jukebox files.
0s [LOG] {
  "DropOnDeath": true,
  "LimbCrushing": true,
  "LimbOverflowExplosion": true,
  "TracerBullets": true,
  "FancyEffects": true,
  "ExpandedGore": false,
  "Decals": true,
  "ClampVolume": true,
  "ShowOutlines": true,
  "LogDebugMessages": false,
  "ShowFramerate": true,
  "Lighting": true,
  "VSync": false,
  "SMAA": false,
  "ZoomSensitivity": 1.0,
  "MasterVolume": 1.0,
  "SfxVolume": 1.0,
  "UserInterfaceVolume": 1.0,
  "AmbienceVolume": 1.0,
  "ShakeIntensity": 1.0,
  "SlowMotionSpeed": 20.0,
  "CrushForceMultiplier": 1.0,
  "DeleteWireByContextMenu": true,
  "SimplifiedBackground": false,
  "AmbientTemperatureTransfer": true,
  "TemperatureUnit": 0,
  "WindowMode": 1,
  "CollisionQuality": 1,
  "TonemappingMode": 0,
  "BloomMode": 2,
  "Brightness": 100.0,
  "PhysicsIterations": 16,
  "RenderScale": 1.0,
  "FramerateLimit": 144,
  "Resolution": null,
  "ShowTutorial": false,
  "ShowModLoadingFreeze": true,
  "RejectShadyCode": true
}
0s [LOG] Started background loading task: Steam Workshop Retrieving list
5.15864s [LOG] Finished background loading task: Steam Workshop Retrieving list
5.15864s [LOG] Started background loading task: Contraptions Reading
5.325021s [LOG] Finished background loading task: Contraptions Reading
5.325021s [LOG] Started background loading task: Contraptions Synchronising
15.82127s [LOG] Finished background loading task: Contraptions Synchronising
15.82127s [LOG] Started background loading task: Destructible Watch Tower Processing
15.85252s [LOG] Finished background loading task: Destructible Watch Tower Processing
15.85252s [LOG] Started background loading task: Scream mod Parsing metadata
15.91811s [LOG] Finished background loading task: Scream mod Parsing metadata
15.91811s [LOG] Started background loading task: Scream mod Processing
15.97349s [LOG] Finished background loading task: Scream mod Processing
15.97349s [LOG] Started background loading task: Futuristic Weapons Mod + (V0.4) [DISCONTINUED FOR A WHILE] Parsing metadata
16.01648s [LOG] Finished background loading task: Futuristic Weapons Mod + (V0.4) [DISCONTINUED FOR A WHILE] Parsing metadata
16.01648s [LOG] Started background loading task: Futuristic Weapons Mod + (V0.4) [DISCONTINUED FOR A WHILE] Processing
16.05391s [LOG] Finished background loading task: Futuristic Weapons Mod + (V0.4) [DISCONTINUED FOR A WHILE] Processing
16.05391s [LOG] Started background loading task: Cryocamera Processing
```

**Comment by mestiez** [comment] 2021-07-30 20:59
duplicate of https://github.com/studio-minus/ppg-bug-reports/issues/1

**Closed by mestiez** 2021-07-30 20:59 UTC
Labels: bug, duplicate
